//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTiendaMascotas.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adopciones
    {
        public int idAdopcion { get; set; }
        public string cedula { get; set; }
        public int idAnimal { get; set; }
        public System.DateTime fechaAdopcion { get; set; }
        public int estadoAdopcion { get; set; }
    
        public virtual Animales Animales { get; set; }
        public virtual EstadoAdopcion EstadoAdopcion1 { get; set; }
    }
}
