//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTiendaMascotas.ModeloBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle
    {
        public long idDetalle { get; set; }
        public long idMaestro { get; set; }
        public int idProducto { get; set; }
        public int cantidad { get; set; }
        public decimal precioCompra { get; set; }
    
        public virtual Maestro Maestro { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
